data:
  train:
  - dataset_dir: null
  val:
  - dataset_dir: null
keypoints:
  bodyparts:
  - nose
  - Left Eye
  - Right Eye
  - LeftEar1
  - LeftEar2
  - RightEar1
  - RightEar2
  - neck
  - body1
  - body2
  - body3
  - tail
  - tail2
  - tail3
  - tail4
  - Front Left 1
  - Front Left 2
  - Front Right 1
  - Front Right 2
  - Back Left 1
  - Back Left 2
  - Back Right 1
  - Back Right 2
  connections:
  - [0, 1]
  - [0, 2]
  - [1, 2]
  - [1, 3]
  - [4, 3]
  - [2, 5]
  - [6, 5]
  - [7, 5]
  - [7, 3]
  - [7, 8]
  - [9, 8]
  - [9, 10]
  - [11, 10]
  - [11, 12]
  - [13, 12]
  - [13, 14]
  - [8, 15]
  - [8, 17]
  - [20, 19]
  - [10, 19]
  - [10, 21]
  - [22, 21]
  - [15, 16]
  - [17, 18]
  name: Mouse Full Body 2
model:
  debug: true
  n_keypoints: 23
  name: null
  pretrained_weights: null
training:
  batch_size: 16
  debug_output: true
  epochs: 20
  learning_rate: 0.01
  num_workers: 1
  sigma: 2.0
